#############################################################################
# Makefile for building: secp256k1.app/Contents/MacOS/secp256k1
# Generated by qmake (3.1) (Qt 6.0.3)
# Project:  secp256k1.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o secp256k1.xcodeproj/project.pbxproj secp256k1.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /usr/local/opt/qt/bin/qmake
secp256k1.xcodeproj/project.pbxproj: secp256k1.pro /usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core_qobject_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/macx-xcode/qmake.conf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/lex.prf \
		secp256k1.pro \
		/usr/local/Cellar/qt/6.0.3_2/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/6.0.3_2/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o secp256k1.xcodeproj/project.pbxproj secp256k1.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_core_qobject_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/macx-xcode/qmake.conf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/6.0.3_2/share/qt/mkspecs/features/lex.prf:
secp256k1.pro:
/usr/local/Cellar/qt/6.0.3_2/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/6.0.3_2/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o secp256k1.xcodeproj/project.pbxproj secp256k1.pro -spec macx-xcode

qmake_all: FORCE

